/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
    export type ReceiptStruct = {seal: BytesLike, claimDigest: BytesLike}

    export type ReceiptStructOutput = [seal: string, claimDigest: string] & {seal: string, claimDigest: string }
  

  export interface MockRISC0VerifierInterface extends Interface {
    getFunction(nameOrSignature: "verify" | "verifyIntegrity"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'verify', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyIntegrity', values: [ReceiptStruct]): string;

    decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyIntegrity', data: BytesLike): Result;
  }

  

  export interface MockRISC0Verifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockRISC0Verifier;
    waitForDeployment(): Promise<this>;

    interface: MockRISC0VerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    verify: TypedContractMethod<
      [seal: BytesLike, imageId: BytesLike, journalDigest: BytesLike, ],
      [void],
      'view'
    >
    

    
    verifyIntegrity: TypedContractMethod<
      [receipt: ReceiptStruct, ],
      [void],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [seal: BytesLike, imageId: BytesLike, journalDigest: BytesLike, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'verifyIntegrity'): TypedContractMethod<
      [receipt: ReceiptStruct, ],
      [void],
      'view'
    >;

    

    filters: {
      
    };
  }