/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockCiphernodeRegistry__factory } from './MockCiphernodeRegistry__factory.js';
export { MockCiphernodeRegistryEmptyKey__factory } from './MockCiphernodeRegistryEmptyKey__factory.js';