/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../../../common.js"
  import type { MockCiphernodeRegistryEmptyKey, MockCiphernodeRegistryEmptyKeyInterface } from "../../../../../../@enclave-e3/contracts/contracts/test/MockCiphernodeRegistry.sol/MockCiphernodeRegistryEmptyKey.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "node",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "numNodes",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "size",
        "type": "uint256"
      }
    ],
    "name": "CiphernodeAdded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "node",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "numNodes",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "size",
        "type": "uint256"
      }
    ],
    "name": "CiphernodeRemoved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "e3Id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes",
        "name": "publicKey",
        "type": "bytes"
      }
    ],
    "name": "CommitteePublished",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "e3Id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "filter",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint32[2]",
        "name": "threshold",
        "type": "uint32[2]"
      }
    ],
    "name": "CommitteeRequested",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "enclave",
        "type": "address"
      }
    ],
    "name": "EnclaveSet",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "committeePublicKey",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "isCiphernodeEligible",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "name": "publishCommittee",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "filter",
        "type": "address"
      },
      {
        "internalType": "uint32[2]",
        "name": "",
        "type": "uint32[2]"
      }
    ],
    "name": "requestCommittee",
    "outputs": [
      {
        "internalType": "bool",
        "name": "success",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061027a8061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061004a575f3560e01c80632e7b716d1461004e5780639ccb58d514610076578063d9bbec9514610089578063e82f3b70146100a0575b5f5ffd5b61006161005c366004610116565b505f90565b60405190151581526020015b60405180910390f35b61006161008436600461012f565b6100bc565b61009e6100973660046101b4565b5050505050565b005b6100ae61005c36600461022d565b60405190815260200161006d565b5f60011973ffffffffffffffffffffffffffffffffffffffff8416016100e357505f6100e7565b5060015b9392505050565b803573ffffffffffffffffffffffffffffffffffffffff81168114610111575f5ffd5b919050565b5f60208284031215610126575f5ffd5b6100e7826100ee565b5f5f5f60808486031215610141575f5ffd5b83359250610151602085016100ee565b915084608085011115610162575f5ffd5b6040840190509250925092565b5f5f83601f84011261017f575f5ffd5b50813567ffffffffffffffff811115610196575f5ffd5b6020830191508360208285010111156101ad575f5ffd5b9250929050565b5f5f5f5f5f606086880312156101c8575f5ffd5b85359450602086013567ffffffffffffffff8111156101e5575f5ffd5b6101f18882890161016f565b909550935050604086013567ffffffffffffffff811115610210575f5ffd5b61021c8882890161016f565b969995985093965092949392505050565b5f6020828403121561023d575f5ffd5b503591905056fea2646970667358221220f6f2d9f619aaf8922a368e22012e8e5ae3e3932f2d9793933a8cc3010dcae6a564736f6c634300081b0033";

  
      type MockCiphernodeRegistryEmptyKeyConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockCiphernodeRegistryEmptyKeyConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockCiphernodeRegistryEmptyKey__factory extends ContractFactory {
    
      constructor(...args: MockCiphernodeRegistryEmptyKeyConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockCiphernodeRegistryEmptyKey & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockCiphernodeRegistryEmptyKey__factory {
      return super.connect(runner) as MockCiphernodeRegistryEmptyKey__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockCiphernodeRegistryEmptyKeyInterface {
      return new Interface(_abi) as MockCiphernodeRegistryEmptyKeyInterface;
    }
    
    override attach(address: string | Addressable): MockCiphernodeRegistryEmptyKey {
      return super.attach(address) as MockCiphernodeRegistryEmptyKey;
    }
  static connect(address: string, runner?: ContractRunner | null): MockCiphernodeRegistryEmptyKey {
      return new Contract(address, _abi, runner) as unknown as MockCiphernodeRegistryEmptyKey;
    }
  }

  
  