/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockCiphernodeRegistry } from './MockCiphernodeRegistry.js';
export type { MockCiphernodeRegistryEmptyKey } from './MockCiphernodeRegistryEmptyKey.js';