/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from './Mocks/index.js';
export type { mocks };
export type { ImageID } from './ImageID.js';
export type { InputValidator } from './InputValidator.js';
export type { MyProgram } from './MyProgram.js';