/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as registry from './registry/index.js';
export type { registry };
import type * as test from './test/index.js';
export type { test };
export type { Enclave } from './Enclave.js';