/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../../../common.js"
  

  export interface MockE3ProgramInterface extends Interface {
    getFunction(nameOrSignature: "ENCRYPTION_SCHEME_ID" | "inputValidator" | "paramsHashes" | "validate" | "verify"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'ENCRYPTION_SCHEME_ID', values?: undefined): string;
encodeFunctionData(functionFragment: 'inputValidator', values?: undefined): string;
encodeFunctionData(functionFragment: 'paramsHashes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validate', values: [BigNumberish, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'verify', values: [BigNumberish, BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'ENCRYPTION_SCHEME_ID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inputValidator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paramsHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  

  export interface MockE3Program extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockE3Program;
    waitForDeployment(): Promise<this>;

    interface: MockE3ProgramInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ENCRYPTION_SCHEME_ID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    inputValidator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paramsHashes: TypedContractMethod<
      [e3Id: BigNumberish, ],
      [string],
      'view'
    >
    

    
    validate: TypedContractMethod<
      [e3Id: BigNumberish, arg1: BigNumberish, e3ProgramParams: BytesLike, computeProviderParams: BytesLike, ],
      [[string, string]],
      'nonpayable'
    >
    

    
    verify: TypedContractMethod<
      [arg0: BigNumberish, arg1: BytesLike, data: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ENCRYPTION_SCHEME_ID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'inputValidator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paramsHashes'): TypedContractMethod<
      [e3Id: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'validate'): TypedContractMethod<
      [e3Id: BigNumberish, arg1: BigNumberish, e3ProgramParams: BytesLike, computeProviderParams: BytesLike, ],
      [[string, string]],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BytesLike, data: BytesLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }