/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mocks from './Mocks/index.js';
export { ImageID__factory } from './ImageID__factory.js';
export { InputValidator__factory } from './InputValidator__factory.js';
export { MyProgram__factory } from './MyProgram__factory.js';