/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegistry__factory } from './IRegistry__factory.js';
export { MockNaiveRegistryFilter__factory } from './MockNaiveRegistryFilter__factory.js';