/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as registry from './registry/index.js';
export * as test from './test/index.js';
export { Enclave__factory } from './Enclave__factory.js';